name: SMARTS CD Docker

on:
  schedule:
    - cron: '30 5,17 * * *'

jobs:
  docker:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: huawei-noah/SMARTS
          path: './SMARTS'
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: ./SMARTS
          file: ./SMARTS/utils/docker/Dockerfile
          repository: huaweinoah/smarts
          tag_with_ref: true
